[package]
name = "uplink"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
transport = { path = "../../transport" }
validate = { path = "../../validate" }
xml-rs = "=0.8.3"
yaserde = "0.7.1"
yaserde_derive = "0.7.1"
