[package]
name = "ws_discovery"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
percent-encoding = "2.1.0"
url = "2.2.1"
xml-rs = "=0.8.3"
yaserde = "0.7.1"
yaserde_derive = "0.7.1"
